---
title: Arch Linux installation guide
author: Rik Ferreira
date: '2021-02-26'
slug: arch-linux-installation
categories:
  - Linux
tags:
  - Linux
  - Arch Linux
subtitle: ''
summary: ''
authors: [admin]
lastmod: '2021-02-26T13:55:22-03:00'
featured: no
image:
  placement: 3
  caption: 'Arch Linux Simply Black wallpaper'
  focal_point: 'center'
  preview_only: no
projects: []
editor_options: 
  chunk_output_type: console
bibliography: bibliography.bib
csl: associacao-brasileira-de-normas-tecnicas.csl
# output:
#   blogdown::html_page:
#     toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, echo = TRUE)
```

The Arch Linux is a distribution focused on minimalism and efficiency, and follows a "do it yourself" philosophy. For giving the user the power to build the system in the way he wants, its installation process may not be trivial to most PC users.

To overcome the complexity of the installation process, there are many solutions like the [Zen Installer](https://github.com/spookykidmm/zen_installer) script or the [ArcoLinux](https://arcolinux.com/) and [Manjaro](https://manjaro.org/) distributions, but I personally prefer the vanilla installation for its simplicity and flexibility.

To help others in the vanilla installation process, I decided to present the steps I usually take when installing the Arch Linux.

This post doesn't intend to be any ultimate installation guide, just a minimal reproducible script that guides my installation process. So I'm assuming that you are aware of the [official installation guide](https://wiki.archlinux.org/index.php/installation_guide) (available in portuguese too).

There are many good tutorials online complementing the official installation guide and my favorites are:

- [Luke Smith tutorial (EN)](https://www.youtube.com/watch?v=4PBqpX0_UOc)
- [Diolinux tutorial (PT)](https://www.youtube.com/watch?v=4orYC5ARfn8&)

My main motivation for writing this post is to present some troubles I had and doesn't were covered in any tutorial I found online. Finally, I will present some of the packages I usually install, like my window manager and text editors.

# Installation

## Initial setup

First, we need to set the correct keyboard layout. To me it is the ABNT2.

```{bash}
loadkeys br-abnt2
```

The Arch Linux installation relies on internet connection. To connect to a wireless network, we may use the `iwctl` command.

```{bash}
iwctl
```

This command will open a prompt where you can interact inside the program. You can list the devices, scan for networks and finally connect to a detected network:

```{bash}
device list # list the devices
station wlp3s0 scan # wlp3s0 is my device, detected with the previous command
station wlp3s0 connect SSID # you will get the SSID of your network with the previous command
```

To verify your connection you can ping the Arch Linux site.

```{bash}
ping archlinux.org
```

## Partitioning the disks

To partition the disks we will use the `fdisk` utility. It has a concise built-in help so I will just describe the concepts behind disk partitions. We (really) need 2 partitions: one for the EFI `/boot` and other for `/`, but it is a good practice to use at least 4.

- /dev/sda1: 512 MB for EFI system partition
- /dev/sda2: 4 GB for Linux swap
- /dev/sda3: 30 GB for /
- /dev/sda4: rest of the space for /home

The official guide recommends at least 260 MB for the `/mnt/boot/efi` partition, but you may need some space later, depending on your necessities.

There isn't any consensus about the size of the swap partition or if a partition is really needed. You may prefer the swap partition over the swap file if you want to share it with other systems and I suggest the square root of the RAM for its size (in my case, square root of 16).

The Arch Linux is a really lightweight distro, and 10 GB may be more than enough for most of the users. I suggest 30 GB, but feel free to change its size.

After creating the partitions we need to format them:

```{bash}
mkfs.fat -F32 /dev/sda1
mkfs.ext4 /dev/sda3
mkfs.ext4 /dev/sda4
mkswap /dev/sda2
```

After that, we need to mount the partitions:

```{bash}
mount /dev/sda3 /mnt
swapon /dev/sda2
mkdir -p /mnt/boot/efi /mnt/home
mount /dev/sda1 /mnt/boot/efi
mount /dev/sda4 /mnt/home
```

This step is important because it will serve as reference to create the `/etc/fstab` file.

## Installing the Arch Linux

Installing the Arch Linux is simple like that:

```{bash}
pacstrap /mnt base base-devel linux linux-firmware git vim sudo
```

After installed, generate the `/etc/fstab` file with the `genfstab` command. Remember to pass the `-U` option for using the UUID @uuid of the partitions. Don't worry, you still can edit the file later, just be sure that it will be OK before rebooting.

```{bash}
genfstab -U /mnt >> /mnt/etc/fstab
```

Then, let's change the root to the mounted driver and set up the system.

```{bash}
arch-chroot /mnt
```

# Changed root

## Clock setup

In the `/usr/share/zoneinfo` directory are the time zones files. With the `ls` command you can identify your region folder and inside it, your time zone file. The `ln` command here will create a symbolic link in the `/etc/localtime` folder.

```{bash}
ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
hwclock --systohc
```

## Hosts file

In the `/etc/hostname` file we will register our pc name. This is the name which will identify the computer in the network.

```{bash}
echo "pcname" >> /etc/hostname
vim /etc/hosts
```

In the `/etc/hosts` we will describe our IP addresses with the hostnames:

```
127.0.0.1      localhost
::1            localhost
127.0.1.1      pcname.localdomain      pcname
```

## Locale

Uncomment your locale in `/etc/locale.gen` file. To me it's the `pt_BR.UTF-8 UTF-8` line. The `locale-gen` command is used to generate the locale.

```{bash}
vim /etc/locale.gen
locale-gen
```

In `/etc/locale.conf` we need to set an environment variable with our locale, and in the `/etc/vconsole.conf` we will set our keyboard layout (to me it is the ABNT 2).

```{bash}
echo "LANG=pt_BR.UTF-8" >> /etc/locale.conf
echo "KEYMAP=br-abnt2" >> /etc/vconsole.conf
```

## Change root password

```{bash}
passwd
```

## Add a user

The `useradd` command is used to create a user. The `-m` option is for creating a folder in `/home` directory and the `-g wheel` is for adding the user to the wheel group.

```{bash}
useradd -m -g wheel user
```

```{bash}
passwd user
```

## Change sudo permissions

To execute commands with super user privileges without going root, we need to install the sudo package. After that, use the `visudo` command to edit the `/etc/sudoers` file. You will be able to edit the file directly, but the `visudo` is the safest way to do that.

```{bash}
sudo EDITOR=vim visudo
```

You may be able to change permissions in the `/etc/sudoers` file just by uncomment some of the existing lines. This is part of my file for reference:

```{bash}
# User privilege specification
root    ALL=(ALL:ALL) ALL

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) NOPASSWD: ALL
```

## Grub installation

First we need to download the grub with pacman.

```{bash}
pacman -S grub efibootmgr
```

After that, for EFI boot, we have to run `grub-install` with `--target`, `--efi-directory` and `--bootloader-id` options set like that:

```{bash}
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=grub
```

To generate the GRUB config file:

```{bash}
grub-mkconfig -o /boot/grub/grub.cfg
```

## Download network utilities

My router sends a 2472 Hz signal, which isn't common in the United States, so I have to make my wireless driver recognize my network with the `crda` utility. __crda__ stands for __central regulatory domain agent__ and relies on ISO standards to communicate with the kernel @crda.

After that, the `networkmanager` and `iw` will be used to configurate the wi-fi network.

```{bash}
pacman -S iw crda networkmanager
```

After downloaded all the network utilities, you are able to reboot and install all the softwares you want. If this is your first time with Arch, you will notice that you only have a black screen with a prompt, this is because we don't have any graphic interface yet. There are plenty of options to install, and you can go for one of the desktop environments (DE) out there or you can simply install a window managers (WM).

I use [bspwm](https://wiki.archlinux.org/index.php/bspwm). This window manager doesn't come with a hotkey daemon or a bar, like [dwm](https://wiki.archlinux.org/index.php/Dwm) or [i3](https://wiki.archlinux.org/index.php/I3), so you have to install them. The xorg is the graphic server, and it is required by any other WM or DE.

## Download the window manager

```{bash}
pacman -S xorg-server xorg-xinit bspwm sxhkd polybar
```

# References
